select ID_AUTO as ID, MARCA from auto

--LISTA DE VENDERORES, VENDEDOR, MARCA MODELO, COLOR Y FECHA DE LOS AUTOS QUE HAYAN SIDO VENDIDOS EN AÑO 2016
select facturacion.n_factura as [NUMERO DE FACTURA], vendedor.NOMB_VENDEDOR as VENDEDOR, auto.MARCA, auto.MODELO,
	auto.COLOR, FACTURACION.FECHA
	from FACTURACION inner join VENDEDOR on FACTURACION.ID_VENDEDOR=VENDEDOR.ID_VENDEDOR
	inner join AUTO on FACTURACION.ID_AUTO=AUTO.ID_AUTO
	where datepart (year, FACTURACION.FECHA)=2016

ALTER TABLE  FACTURACION ADD FECHA DATE

--select * from FACTURACION

--truncate table facturacion

INSERT INTO [dbo].[FACTURACION] VALUES(5,15,22,51,1,13254.25,'02-01-2019')
INSERT INTO [dbo].[FACTURACION] VALUES(4,17,25,52,1,25458.78,'04-03-2018')
INSERT INTO [dbo].[FACTURACION] VALUES(1,11,25,53,2,43600.49,'09-03-2016')
INSERT INTO [dbo].[FACTURACION] VALUES(3,12,21,54,1,1650.50,'01-05-2016')
INSERT INTO [dbo].[FACTURACION] VALUES(6,14,23,55,1,7500.60,'02-08-2017')
INSERT INTO [dbo].[FACTURACION] VALUES(2,16,24,56,1,36857.25,'01-06-2016')


select * from PEDIDO
select * from PROVEEDOR

select * from FACTURACION

select facturacion.n_factura as [NUMERO DE FACTURA], vendedor.NOMB_VENDEDOR as VENDEDOR, auto.MARCA, auto.MODELO,
	auto.COLOR, FACTURACION.FECHA, count (vendedor.ID_VENDEDOR) as [TOTAL DE AUTOS VENDIDOS]
	from FACTURACION inner join VENDEDOR on FACTURACION.ID_VENDEDOR=VENDEDOR.ID_VENDEDOR
	inner join AUTO on FACTURACION.ID_AUTO=AUTO.ID_AUTO
	group by VENDEDOR.ID_VENDEDOR

--CONSULTAR EL NOMBRE DEL VENDEDOR Y EL NUMERO DE VEHICULOS QUE HA VENDIDO
select VENDEDOR.NOMB_VENDEDOR AS VENDEDOR, count (vendedor.NOMB_VENDEDOR) as [TOTAL DE AUTOS VENDIDOS]
	from FACTURACION inner join VENDEDOR on FACTURACION.ID_VENDEDOR=VENDEDOR.ID_VENDEDOR
	inner join AUTO on FACTURACION.ID_AUTO=AUTO.ID_AUTO
	group by VENDEDOR.NOMB_VENDEDOR

--LISTAR EL NOMBRE DE LOS PROVEEDORES CUYO NUMERO DE AUTOS SEA >2
select PROVEEDOR.NOMB_PROV as PROVEEDOR, PEDIDO.CANTIDAD_AUTOS as [NUMERO DE AUTOS]
	FROM PROVEEDOR inner join PEDIDO on PROVEEDOR.ID_PROVEEDOR = PEDIDO.ID_PROVEEDOR
	where PEDIDO.CANTIDAD_AUTOS >2